package com.example.platform.task.dto;

import com.example.platform.task.model.TaskEntity;
import java.time.LocalDateTime;

public record TaskDetailResponse(
        Long id,
        Long sceneId,
        Long repoId,
        String sceneName,
        String repositoryName,
        String status,
        boolean detailAvailable,
        String triggerType,
        String triggerUser,
        String triggerReason,
        String branch,
        String commitSha,
        String currentStage,
        String resultCode,
        boolean cancelRequested,
        String cancelRequestedBy,
        LocalDateTime startedAt,
        LocalDateTime finishedAt,
        Long durationMs,
        String runnerName,
        String logUrl,
        String resolvedBranch,
        String resolvedBrowser,
        String resolvedEnvJson,
        String resolvedMatchValue,
        String resolvedTestRoot,
        String resolvedRunCommand,
        int environmentVariableCount,
        int artifactCount,
        boolean hasArtifacts) {

    public static TaskDetailResponse from(
            TaskEntity task,
            String sceneName,
            String repositoryName,
            int environmentVariableCount,
            int artifactCount) {
        return new TaskDetailResponse(
                task.getId(),
                task.getSceneId(),
                task.getRepoId(),
                sceneName,
                repositoryName,
                task.getStatus(),
                !"RUNNING".equalsIgnoreCase(task.getStatus()) && !"QUEUED".equalsIgnoreCase(task.getStatus()),
                task.getTriggerType(),
                task.getTriggerUser(),
                task.getTriggerReason(),
                task.getBranch(),
                task.getCommitSha(),
                task.getCurrentStage(),
                task.getResultCode(),
                Boolean.TRUE.equals(task.getCancelRequested()),
                task.getCancelRequestedBy(),
                task.getStartedAt(),
                task.getFinishedAt(),
                task.getDurationMs(),
                task.getRunnerName(),
                task.getLogUrl(),
                task.getResolvedBranch(),
                task.getResolvedBrowser(),
                task.getResolvedEnvJson(),
                task.getResolvedMatchValue(),
                task.getResolvedTestRoot(),
                task.getResolvedRunCommand(),
                environmentVariableCount,
                artifactCount,
                artifactCount > 0);
    }
}
