spring:
  datasource:
    url: ${PLATFORM_DB_URL:jdbc:mysql://localhost:3306/playwright_platform?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${PLATFORM_DB_USERNAME:root}
    password: ${PLATFORM_DB_PASSWORD:12345678}
platform:
  runner:
    mode: ${PLATFORM_RUNNER_MODE:local}
  storage:
    minio:
      endpoint: ${PLATFORM_MINIO_ENDPOINT:http://127.0.0.1:9000}
      access-key: ${PLATFORM_MINIO_ACCESS_KEY:minioadmin}
      secret-key: ${PLATFORM_MINIO_SECRET_KEY:minioadmin}
