spring:
  datasource:
    url: ${PLATFORM_DB_URL}
    username: ${PLATFORM_DB_USERNAME}
    password: ${PLATFORM_DB_PASSWORD}
platform:
  runner:
    mode: ${PLATFORM_RUNNER_MODE:local}
  storage:
    minio:
      endpoint: ${PLATFORM_MINIO_ENDPOINT}
      access-key: ${PLATFORM_MINIO_ACCESS_KEY}
      secret-key: ${PLATFORM_MINIO_SECRET_KEY}
